---
  services:
    node1:
      build: .
      container_name: ansible-node1
      ports:
        - "2221:22"

    node2:
      build: .
      container_name: ansible-node2
      ports:
        - "2222:22"

    node3:
      build: .
      container_name: ansible-node3
      ports:
        - "2223:22"